title: "Welcome to LoopZero Tech Apps"
email: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mds.github.io" # the base hostname & protocol for your site

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown

permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
